#!/bin/bash

set -e

echo "Setting up prereqs..."
apt-get update -y
apt-get install software-properties-common -y
curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

echo "Installing terraform..."
apt-get update -y
apt-get install terraform=0.13.5 -y
apt-get install consul-enterprise=1.8.5+ent -y

echo "Cloning assets..."
git clone https://github.com/timarenz/instruqt-consul-zero-trust-networking-with-service-mesh
cp -r instruqt-consul-zero-trust-networking-with-service-mesh/assets/terraform .
rm -rf instruqt-consul-zero-trust-networking-with-service-mesh
cp terraform/introducing-hashicups/files/consul.png /var/www/html/assets/consul.png
cp terraform/introducing-hashicups/files/hashicorp.png /var/www/html/assets/hashicorp.png

echo "Setting up variables..."
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

echo "Running terraform..."
echo $INSTRUQT_GCP_PROJECT_ON_PREM_SERVICE_ACCOUNT_KEY | base64 -d > /root/terraform/gcp-on-prem-creds.json

cat <<EOF > /root/terraform/introducing-hashicups/terraform.tfvars
gcp_project="$(echo $INSTRUQT_GCP_PROJECT_ON_PREM_PROJECT_ID)"
gcp_credentials="/root/terraform/gcp-on-prem-creds.json"
EOF

cd /root/terraform/introducing-hashicups
terraform init
terraform apply -auto-approve
terraform output -json>output.json


echo "export CONSUL_HTTP_ADDR=$(cat output.json | jq -r '.consul_http_addr.value')" >> /root/.bashrc
echo "export CONSUL_HTTP_TOKEN=$(cat output.json | jq -r '.consul_master_token.value')" >> /root/.bashrc

head -n 15 /var/www/html/index.html > /var/www/html/target.html
cat <<EOF >> /var/www/html/target.html
<div class="account hashicups">
  <div class="card">
    <div class="header">
      <div class="logo">
        <img alt="icon" src="/assets/hashicorp.png">
      </div>
      <div class="title">
        <h2>on-prem</h2>
        <p>HashiCups</p>
      </div>
    </div>
    <div class="properties">
      <div class="key">HashiCups URL:</div>
      <div class="value">
        <a href="http://$(cat output.json | jq -r '.frontend_server_public_ip.value')"
          target="_blank">
          http://$(cat output.json | jq -r '.frontend_server_public_ip.value')
        </a>
      </div>
    </div>
  </div>
</div>
EOF
cat <<EOF >> /var/www/html/target.html
<div class="account consul">
  <div class="card">
    <div class="header">
      <div class="logo">
        <img alt="icon" src="/assets/consul.png">
      </div>
      <div class="title">
        <h2>on-prem</h2>
        <p>Consul</p>
      </div>
    </div>
    <div class="properties">
      <div class="key">Consul URL:</div>
      <div class="value">
        <a href="$(cat output.json | jq -r '.consul_http_addr.value')"
          target="_blank">
          $(cat output.json | jq -r '.consul_http_addr.value')
        </a>
      </div>
      <div class="key">Master Token:</div>
      <div class="value" data-copyable>$(cat output.json | jq -r '.consul_master_token.value')</div>
    </div>
  </div>
</div>
EOF
tail -n +15 /var/www/html/index.html >> /var/www/html/target.html
mv -f /var/www/html/target.html /var/www/html/index.html

# /usr/sbin/service nginx restart
